### ISSUE TITLE
Change stylelint and stylelint-webpack-plugin to peerDependencies

### ISSUE THREAD

**Issue by jackwilsdon** [Ehres/react-app-rewire-stylelint#2]
In it's current state, we can't use a newer version of stylelint without updating this package. It'd be nice to have these moved into `peerDependencies` instead so that users can define their own version in their `package.json`.

I can create a PR for this if you're open to the idea @Ehres.

**Comment by Ehres** [comment]
Hello, yeah I'm open you can create PR

**Comment by Ehres** [comment]
fixed by #3
